### ISSUE TITLE
Potentially unwanted side effects

### ISSUE THREAD

**Issue by flangknecht** [Stefan-Kosker/totally-legal-blitzermelder#2]
https://github.com/Stefan-Kosker/totally-legal-blitzermelder/blob/b366ca9d5b6efe8cbd4451c6c6ede84993ca335d/MotorbikeEnhancher3000/FullProject/main/Fuel.h#L14-L17

This may lead to all sorts of unexpected behavior, especially because it's being called from within a getter where being free of side-effects is a reasonable assumption

**Comment by Stefan-Kosker** [comment]
This is actually the official fix for a known sideeffect of ` analogReference(DEFAULT); `. Changing analogReference on the fly causes getting wrong Values from analogRead from first time (almost always) and second time (sometimes) third reading is okay.
